trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - tricor-landing-zone/<azure_repo_subscription_folder>

variables:
- group: vgp-tricor-landing-zone-terraform
- name: pipeline.workingDirectory
  value: 'tricor-landing-zone/<azure_repo_subscription_folder>'
- name: pipeline.environment
  value: '<azure_pipeline_environment_name>'

pool:
  vmImage: ubuntu-latest

stages:
- template: template-terraform-deploy.yml