trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - tricor-landing-zone/tricor-hk-lz-pd

variables:
- group: vgp-tricor-landing-zone-terraform
- name: pipeline.workingDirectory
  value: 'tricor-landing-zone/tricor-hk-lz-pd'
- name: pipeline.environment
  value: 'tricor-landing-zone-hk-lz-pd'

pool:
  vmImage: ubuntu-latest

stages:
- template: template-terraform-deploy.yml