trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - tricor-landing-zone/tricor-hk-lz-np

variables:
- group: vgp-tricor-landing-zone-terraform
- name: pipeline.workingDirectory
  value: 'tricor-landing-zone/tricor-hk-lz-np'
- name: pipeline.environment
  value: 'tricor-landing-zone-hk-lz-np'

pool:
  vmImage: ubuntu-latest

stages:
- template: template-terraform-deploy.yml