trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - tricor-management

variables:
- group: vgp-tricor-landing-zone-terraform
- name: pipeline.workingDirectory
  value: 'tricor-management'
- name: pipeline.environment
  value: 'tricor-platform-management'

pool:
  vmImage: ubuntu-latest

stages:
- template: template-terraform-deploy.yml